//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTracker.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaffTracker.Resources.Translations.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Export.
        /// </summary>
        public static string DayExport {
            get {
                return ResourceManager.GetString("DayExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportDialogTitle {
            get {
                return ResourceManager.GetString("ExportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during export.
        /// </summary>
        public static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Folder.
        /// </summary>
        public static string ExportFolder {
            get {
                return ResourceManager.GetString("ExportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export created successfully.
        /// </summary>
        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Type.
        /// </summary>
        public static string ExportType {
            get {
                return ResourceManager.GetString("ExportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string ExportType_Day {
            get {
                return ResourceManager.GetString("ExportType_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string ExportType_Month {
            get {
                return ResourceManager.GetString("ExportType_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string ExportType_Range {
            get {
                return ResourceManager.GetString("ExportType_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string ExportType_Year {
            get {
                return ResourceManager.GetString("ExportType_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a date or year.
        /// </summary>
        public static string ExportValidationError {
            get {
                return ResourceManager.GetString("ExportValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error selecting folder.
        /// </summary>
        public static string FileSelectionError {
            get {
                return ResourceManager.GetString("FileSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entries found for the selected period.
        /// </summary>
        public static string NoEntriesToExport {
            get {
                return ResourceManager.GetString("NoEntriesToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Exported File.
        /// </summary>
        public static string OpenExportedFile {
            get {
                return ResourceManager.GetString("OpenExportedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select End Date.
        /// </summary>
        public static string SelectEndDate {
            get {
                return ResourceManager.GetString("SelectEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Month.
        /// </summary>
        public static string SelectMonth {
            get {
                return ResourceManager.GetString("SelectMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Start Date.
        /// </summary>
        public static string SelectStartDate {
            get {
                return ResourceManager.GetString("SelectStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Year.
        /// </summary>
        public static string SelectYear {
            get {
                return ResourceManager.GetString("SelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default File Name.
        /// </summary>
        public static string Settings_ExportDefaultFileName {
            get {
                return ResourceManager.GetString("Settings_ExportDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Download Folder.
        /// </summary>
        public static string Settings_ExportPreferredDownloadDestination {
            get {
                return ResourceManager.GetString("Settings_ExportPreferredDownloadDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Settings.
        /// </summary>
        public static string Settings_ExportSettings {
            get {
                return ResourceManager.GetString("Settings_ExportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new after save.
        /// </summary>
        public static string Settings_FormCreateNew {
            get {
                return ResourceManager.GetString("Settings_FormCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Disabled: the system redirects to the list of entries.
        /// </summary>
        public static string Settings_FormCreateNew_Tooltip_Disabled {
            get {
                return ResourceManager.GetString("Settings_FormCreateNew_Tooltip_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Enabled: the user remains on the entry creation page.
        /// </summary>
        public static string Settings_FormCreateNew_Tooltip_Enabled {
            get {
                return ResourceManager.GetString("Settings_FormCreateNew_Tooltip_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls system behaviour after successfully creating a new entry:.
        /// </summary>
        public static string Settings_FormCreateNew_Tooltip_Header {
            get {
                return ResourceManager.GetString("Settings_FormCreateNew_Tooltip_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Company.
        /// </summary>
        public static string Settings_FormFieldCompany {
            get {
                return ResourceManager.GetString("Settings_FormFieldCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Division.
        /// </summary>
        public static string Settings_FormFieldDivision {
            get {
                return ResourceManager.GetString("Settings_FormFieldDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Entry Date.
        /// </summary>
        public static string Settings_FormFieldEntryDate {
            get {
                return ResourceManager.GetString("Settings_FormFieldEntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Settings.
        /// </summary>
        public static string Settings_FormSettings {
            get {
                return ResourceManager.GetString("Settings_FormSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid State.
        /// </summary>
        public static string Settings_GridState {
            get {
                return ResourceManager.GetString("Settings_GridState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save grid filters.
        /// </summary>
        public static string Settings_GridStateFiltersSaving {
            get {
                return ResourceManager.GetString("Settings_GridStateFiltersSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save hidden columns.
        /// </summary>
        public static string Settings_GridStateHiddenColumnsSaving {
            get {
                return ResourceManager.GetString("Settings_GridStateHiddenColumnsSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save page number.
        /// </summary>
        public static string Settings_GridStatePageIndexSaving {
            get {
                return ResourceManager.GetString("Settings_GridStatePageIndexSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save page size.
        /// </summary>
        public static string Settings_GridStatePageSizeSaving {
            get {
                return ResourceManager.GetString("Settings_GridStatePageSizeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save grid sorting.
        /// </summary>
        public static string Settings_GridStateSortsSaving {
            get {
                return ResourceManager.GetString("Settings_GridStateSortsSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Export.
        /// </summary>
        public static string YearExport {
            get {
                return ResourceManager.GetString("YearExport", resourceCulture);
            }
        }
    }
}
