//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffTracker.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StaffTracker.Resources.Translations.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new after save.
        /// </summary>
        public static string Settings_FormCreateNew {
            get {
                return ResourceManager.GetString("Settings_FormCreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Disabled: the system redirects to the list of entries.
        /// </summary>
        public static string Settings_FormCreateNew_Tooltip_Disabled {
            get {
                return ResourceManager.GetString("Settings_FormCreateNew_Tooltip_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Enabled: the user remains on the entry creation page.
        /// </summary>
        public static string Settings_FormCreateNew_Tooltip_Enabled {
            get {
                return ResourceManager.GetString("Settings_FormCreateNew_Tooltip_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls system behaviour after successfully creating a new entry:.
        /// </summary>
        public static string Settings_FormCreateNew_Tooltip_Header {
            get {
                return ResourceManager.GetString("Settings_FormCreateNew_Tooltip_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Company.
        /// </summary>
        public static string Settings_FormFieldCompany {
            get {
                return ResourceManager.GetString("Settings_FormFieldCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Division.
        /// </summary>
        public static string Settings_FormFieldDivision {
            get {
                return ResourceManager.GetString("Settings_FormFieldDivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Entry Date.
        /// </summary>
        public static string Settings_FormFieldEntryDate {
            get {
                return ResourceManager.GetString("Settings_FormFieldEntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Settings.
        /// </summary>
        public static string Settings_FormSettings {
            get {
                return ResourceManager.GetString("Settings_FormSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid State.
        /// </summary>
        public static string Settings_GridState {
            get {
                return ResourceManager.GetString("Settings_GridState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save grid filters.
        /// </summary>
        public static string Settings_GridStateFiltersSaving {
            get {
                return ResourceManager.GetString("Settings_GridStateFiltersSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save hidden columns.
        /// </summary>
        public static string Settings_GridStateHiddenColumnsSaving {
            get {
                return ResourceManager.GetString("Settings_GridStateHiddenColumnsSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save page number.
        /// </summary>
        public static string Settings_GridStatePageIndexSaving {
            get {
                return ResourceManager.GetString("Settings_GridStatePageIndexSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save page size.
        /// </summary>
        public static string Settings_GridStatePageSizeSaving {
            get {
                return ResourceManager.GetString("Settings_GridStatePageSizeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save grid sorting.
        /// </summary>
        public static string Settings_GridStateSortsSaving {
            get {
                return ResourceManager.GetString("Settings_GridStateSortsSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
    }
}
